services:
  - type: web
    name: fintech-transaction-intelligence-api
    runtime: node
    plan: free
    buildCommand: npm ci && npm run prisma:generate && npm run build
    startCommand: npm run prisma:migrate && npm run start:prod
    healthCheckPath: /health
    envVars:
      - key: NODE_VERSION
        value: 22.16.0
      - key: DATABASE_URL
        sync: false
      - key: DIRECT_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: GEMINI_API_KEY
        sync: false
